exclude: [ Gemfile, Gemfile.lock ]
name: fronx.github.io
markdown: redcarpet
pygments: true
permalink: /:year-:month-:day--:title
name: fronx.github.io
description: I write about programming.
url: http://fronx.github.io/
